### ISSUE TITLE
InvalidateCacheDependencies for .Include queries

### ISSUE THREAD

**Issue by szavoda** [VahidN/EFSecondLevelCache.Core#10]
Hi - 

I am trying to understand a little about invalidating cache entries in my scenario.  I have a Customer entity that ".Includes" several related entities such as Address and Phone during a GetCustomer operation.

I have been noticing that when I add / update a Phone record, for instance, a subsequent GetCustomer call does not reflect the new / changed records.

Is there a best practices way that you can recommend to invalidate the cache of the related object?

Thanks!

Shawn

**Comment by VahidN** [comment]
- I have some tests about these included entities [here](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.Tests/EFCachedQueryProviderInvalidationTests.cs). 
- Also debug this line [_cacheServiceProvider.InvalidateCacheDependencies](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.AspNetCoreSample/DataLayer/SampleContext.cs#L120) in your code. does `changedEntityNames` contain your newly changed entity names?
- At the end you can always force the whole cache to refresh by calling `_cacheServiceProvider.ClearAllCachedEntries()`.

**Comment by szavoda** [comment]
In my Customer -> Phone example above, a change to the Phone entity does not show the Customer Entity in the changedEntityNames variable.  I can see in the tests where you are testing for my scenario, however.

I wonder if I have set something up improperly with the entity so that the context does not recognize the relationship.

I want to avoid invalidating the entire cache.  Temporarily, I am going to pass an optional parameter to SaveChanges() that will include the additional entities to invalidate the cache for.

**Comment by VahidN** [comment]
Please provide a failing test to study it, something like the mentioned tests.

**Comment by VahidN** [comment]
Tip-2: How to find the detected cache dependecies of a query:
```csharp
var debugInfo = new EFCacheDebugInfo();
var list = context.Products.Cacheable(debugInfo).ToList();
var cacheDependencies = debugInfo2.EFCacheKey.CacheDependencies;
```
