### ISSUE TITLE
Does the example you have work with the standard library

### ISSUE THREAD

**Issue by aday12345** [VahidN/EFSecondLevelCache.Core#11]
I used to have this working in 1.x but just recently started to move to 2.x.

I think I am missing a ref cause vs2017 complains about:

.WithMicrosoftMemoryCacheHandle()
.WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(10))

not sure what i am missing, at one point you had an example for the standard library but don't see it anymore

**Comment by VahidN** [comment]
[EFSecondLevelCache.Core.AspNetCoreSample](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.AspNetCoreSample/EFSecondLevelCache.Core.AspNetCoreSample.csproj#L18) has been upgraded to ASP.NET Core 2.0. Check out its references to see what's missing.

**Comment by aday12345** [comment]
got it, thanks for your help

some how I added 

CacheManager.Microsoft.Extensions.Configuration not CacheManager.Microsoft.Extensions.Caching.Memory

thanks again for your help
