### ISSUE TITLE
Anything like this available for EF6 / .NET Framework?

### ISSUE THREAD

**Issue by RudeySH** [VahidN/EFSecondLevelCache.Core#21]
The documentation mentions the following:

> This cache is updated when an entity is changed (insert, update, or delete) via a DbContext that uses this library.

Is anything like this implemented in any of the available EF6 libraries that you know of? I'm not using .NET Core unfortunately.

**Comment by RudeySH** [comment]
It seems [EFCache](https://github.com/moozzyk/EFCache/issues/30#issuecomment-403226809) does what I was looking for.

**Comment by VahidN** [comment]
- You can use .NET Standard libraries from .NET full apps.
- Also there is an EF 6 version of this library here: https://github.com/VahidN/EFSecondLevelCache
