### ISSUE TITLE
Keys not being generated

### ISSUE THREAD

**Issue by attiqeurrehman** [VahidN/EFSecondLevelCache.Core#22]
# Summary of the issue

I am unable to get the correct response from the Redis Cache,  it's not creating the collection of keys or creating other keys once it already has the keys for any other get request. 

## Environment

```
The in-use version: 1.6.1
Operating system: Windows 10
IDE: VS 2017
```

## Example code/Steps to reproduce:

1. Add a couple of Employees
2. Copy & Paste any Id from the Get All request to the Get By Id
3. See the Redis Cache 
4. Try a couple of other Ids and check the results both on Redis and response you get

[Opiniated.zip](https://github.com/VahidN/EFSecondLevelCache.Core/files/2249775/Opiniated.zip)

## Output:

I am not getting the correct response.

**Comment by VahidN** [comment]
It won't work with ProjectTo of auto-mapper. the Cacheable method needs to evaluate the expression tree to find dependencies and also its hash and it's not possible with the ProjectTo method.

**Comment by attiqeurrehman** [comment]
But I have removed it from the get single request handler. I am using ahtomapper after I have the result and it caches first item but not the other items. 

-A

**Comment by attiqeurrehman** [comment]
Following is the code for `RestSingleGetHandler`

```c#
protected override async Task<TSingleGetModel> OnHandleAsync(
            RestSingleGetRequest<TEntity, TSingleGetModel> message,
            CancellationToken cancellationToken)
        {
            var ret = await UnitOfWork.GetRepository<TEntity>()
                .GetAll()
                .Cacheable()
                .FirstOrDefaultAsync(e => e.Id == message.Id, cancellationToken);

            if (ret == null) throw new EntityNotFoundException(typeof(TEntity), message.Id);

            return Mapper.Map<TSingleGetModel>(ret);
        }
```

It works for the first time and create cache in Redis but for next requests it gives weird results.

**Comment by VahidN** [comment]
don't use it if doen't work with your over engineered solution with its 100 dependencies.
