### ISSUE TITLE
ToSql to slow, why not use Experession string=

### ISSUE THREAD

**Issue by SteffenMangold** [VahidN/EFSecondLevelCache.Core#26]
# Summary of the issue

I have a more general question.

The `ToSql` function you are using is very very very slow. It brings an extreme high CPU workload to a heavy cache using service.

Why you don't use the `_query.Expression.ToString()` function as base to build the hash value for an IQueryable? I think it gives us to exact the same result but at much higher speed?
Is there some point I'm missing?

**Comment by VahidN** [comment]
Nice finding! I used the `ToSql` method because it gave me the parameter values, not just a raw expression without any details. But it seems `_query.Expression.ToString()` gives the same result and contains the parameter values as well.

**Comment by SteffenMangold** [comment]
> Nice finding! I used the `ToSql` method because it gave me the parameter values, not just a raw expression without any details. But it seems `_query.Expression.ToString()` gives the same result and contains the parameter values as well.

I think you have to reopen it. There is a problem with some parameter values.
The complete problem is descript here:
https://petemontgomery.wordpress.com/2008/08/07/caching-the-results-of-linq-queries/

There is also a logic to solve this. But it needs some more implementation.

**Comment by SteffenMangold** [comment]
I also created a question for the EF team. Maybe there is another solution.
https://github.com/aspnet/EntityFrameworkCore/issues/14230
