### ISSUE TITLE
EFSecondLevelCache.Core for .net 4.5.1

### ISSUE THREAD

**Issue by aday12345** [VahidN/EFSecondLevelCache.Core#3]
currently i am using efcore v1.1.0 with .net v4.5.1 is there any chance you will have a version of EFSecondLevelCache.Core that will work with 4.5+ I was able to use EFSecondLevelCache but that also pulls in ef 6.1.3 as a dependency that i do not need.

**Comment by VahidN** [comment]
Downgraded the project to use `.NETStandard 1.3`. Now it should be compatible with .net v4.5.1 via https://github.com/VahidN/EFSecondLevelCache.Core/commit/e8ad4f6a993dc8fe26b9bdae5d99a4eb3eced727
```
PM>Update-Package
```

**Comment by aday12345** [comment]
Ok,  just to be clear I should download the code and code compile it to 1.3 instead of using nuget

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by VahidN** [comment]
The updated NuGet package contains the compiled version against the `.NETStandard 1.3`.

**Comment by aday12345** [comment]
Thank you

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by aday12345** [comment]
Sorry one other question do u have a sample Context I am having trouble setting up the SaveChanges override specifically the part to InvalidateCacheDependencies


Any help would be appreciated thanks.

**Comment by VahidN** [comment]
Yes. Follow the [EFSecondLevelCache.Core.AspNetCoreSample](https://github.com/VahidN/EFSecondLevelCache.Core/tree/master/src/Tests/EFSecondLevelCache.Core.AspNetCoreSample). Specially its [SampleContext](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.AspNetCoreSample/DataLayer/SampleContext.cs#L121) and [Startup](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.AspNetCoreSample/Startup.cs#L27) classes.

**Comment by aday12345** [comment]
Thanks, for your help.

I must be missing something cause my app is not built on  aspnetcore it is a 4.6.1 console app the is using a efcore (4.6.1) dll so I do not have a startup class etc…

To be honest I would like to be able to configure the EFCacheServiceProvider in my efcore contect class instead of injecting it. Does that make sense?

Here is my context that I have with my old code commented out (using the none core version of EFCacheServiceProvider).

    public partial class IveyCoreContext
    {

        public IveyCoreContext(string connection = "", bool enableNoTracking = false) : base(GetDbContextOptions(connection))
        {

            //https://docs.microsoft.com/en-us/ef/core/querying/tracking
            if (enableNoTracking == true)
            {
                this.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
            }

        }

        public override int SaveChanges()
        {
            this.ChangeTracker.DetectChanges();
            var changedEntityNames = this.GetChangedEntityNames();

            var result = base.SaveChanges();
            EFCacheServiceProvider test = new EFCacheServiceProvider()



            return result;
        }

        //public override int SaveChanges()
        //{
        //    return SaveAllChanges(invalidateCacheDependencies: true);
        //}

        //public int SaveAllChanges(bool invalidateCacheDependencies = true)
        //{
        //    var changedEntityNames = getChangedEntityNames();
        //    var result = base.SaveChanges();
        //    if (invalidateCacheDependencies)
        //    {
        //        new EFCacheServiceProvider().InvalidateCacheDependencies(changedEntityNames);
        //    }
        //    return result;
        //}

        //private string[] getChangedEntityNames()
        //{

        //    return this.ChangeTracker.Entries()
        //        .Where(x => x.State == EntityState.Added ||
        //                    x.State == EntityState.Modified ||
        //                    x.State == EntityState.Deleted)
        //        .Select(x => System.Data.Entity.Core.Objects.ObjectContext.GetObjectType(x.Entity.GetType()).FullName)
        //        .Distinct()
        //        .ToArray();
        //}

        private static DbContextOptions GetDbContextOptions(string connection)
        {

            var dbContextOptionsBuilder = new DbContextOptionsBuilder();

            if (connection == string.Empty)
            {
                var serviceProvider = new ServiceCollection().AddEntityFrameworkInMemoryDatabase().BuildServiceProvider();
                dbContextOptionsBuilder.UseInMemoryDatabase().UseInternalServiceProvider(serviceProvider);
            }
            else
            {
                dbContextOptionsBuilder.UseSqlServer(connection);
            }

            var dbContextOptions = dbContextOptionsBuilder.Options;

            return dbContextOptions;
        }

        private static void Initialize()
        {
            //this
        }

    }
}

**Comment by VahidN** [comment]
Follow [EFSecondLevelCache.Core.NET46Sample](https://github.com/VahidN/EFSecondLevelCache.Core/tree/master/src/Tests/EFSecondLevelCache.Core.NET46Sample/EFSecondLevelCache.Core.NET46Sample).
