### ISSUE TITLE
Cache Doesn't Appear to Flush After SaveChanges()

### ISSUE THREAD

**Issue by twurm** [VahidN/EFSecondLevelCache.Core#32]
# Summary of the issue
We are running into what appears to be a cache flush issue when a new record is added.  In our case we query a table for a record something simple: 
```csharp
var debugger = new EFCacheDebugInfo();
(IQueryable).Where(x=>x.Column1 == "ABC" && x.Column2="XYZ").Cacheable(debugger).FirstOrDefault()
```
The result is null which is expected, since the result is null we go to another table and load the record.  SaveChanges is called and `InvalidateCacheDependencies(changedEntityNames);` fires as expected, changedEntityNames contains the changed entity.  We even tried using `ClearAllCachedEntries()` but the result was the same.

Later when we query for that record again the we are getting null back still and `debugger.IsCacheHit == true`.  We are expecting IsCacheHit to be false and the query to go back to the database and get the newly added entity.  

If we restart the app after the record is added everything works correctly, which is why we are leaning towards the cache flushing.

The app in question is a .Net Core Console app (v.2.2) using a .Net Standard 2.0 library dll where the caching takes place.  The dll is a plugin, and loaded via MEF.

We have configured the second level cache in ConfigureServices like so:
```csharp
// Add an in-memory cache service provider 
services.AddEFSecondLevelCache();
services.AddSingleton(typeof(ICacheManager<>), typeof(BaseCacheManager<>));
services.AddSingleton(typeof(ICacheManagerConfiguration),
   new CacheManager.Core.ConfigurationBuilder("Mx.DataLoad")
      .WithJsonSerializer()
      .WithMicrosoftLogging(loggerFactory)
      .WithMicrosoftMemoryCacheHandle()
      .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(Configuration.GetValue("Caching:ExpirationInMinutes", 60)))
   .Build());

// Additional code to spin up our ServiceProvider
var serviceProvider = services.BuildServiceProvider();
EFServiceProvider.ApplicationServices = serviceProvider;
```
## Environment

```
The in-use version: 1.7.1
Operating system: Windows 10
IDE: VS 2017
```
#### Packages
```xml
<PackageReference Include="EFSecondLevelCache.Core" Version="1.7.1" />
<PackageReference Include="CacheManager.Core" Version="1.2.0" />
<PackageReference Include="CacheManager.Microsoft.Extensions.Caching.Memory" Version="1.2.0" />
<PackageReference Include="CacheManager.Serialization.Json" Version="1.2.0" />
<PackageReference Include="CacheManager.Microsoft.Extensions.Logging" Version="1.2.0" />
```

## Questions
Is there a way to visualize the cache so we can see what is going on at each step?

Any suggestions on where to look to isolate the issue?

**Comment by VahidN** [comment]
- If even `ClearAllCachedEntries()` doesn't work for your scenario, it means your caching mechanism doesn't act as a singleton and you have multiple instances of it.
-  You can try using [the Redis](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.Tests/TestsBase.cs#L95) instead of the memory cache. Because it's an external cache store and there will be only one instance of it, also you can query its records very easily to see what's stored in it:
![redis01](https://cloud.githubusercontent.com/assets/766010/25064928/c439a384-221a-11e7-8b9d-4317701243ca.png)

**Comment by twurm** [comment]
@VahidN I figured it out, I was using '.WithMicrosoftMemoryCacheHandle()' but when I switched to 'WithMicrosoftMemoryCacheHandle("AnyString")' things worked correctly.  A full example is below.
```csharp
// Add an in-memory cache service provider 
services.AddEFSecondLevelCache();
services.AddSingleton(typeof(ICacheManager<>), typeof(BaseCacheManager<>));
services.AddSingleton(typeof(ICacheManagerConfiguration),
   new CacheManager.Core.ConfigurationBuilder("Mx.DataLoad")
      .WithJsonSerializer()
      .WithMicrosoftLogging(loggerFactory)
      //.WithMicrosoftMemoryCacheHandle() this didn't work
      .WithMicrosoftMemoryCacheHandle("AnyString") // This works perfectly
      .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(Configuration.GetValue("Caching:ExpirationInMinutes", 60)))
   .Build());

// Additional code to spin up our ServiceProvider
var serviceProvider = services.BuildServiceProvider();
EFServiceProvider.ApplicationServices = serviceProvider;
```

**Comment by twurm** [comment]
@VahidN once we rolled out the fix we still see it in Test, must have been pilot error in dev testing.+

**Comment by VahidN** [comment]
Hopefuly V1.8.1 fixes this issue. Now caching mechanism acts as a true singleton!
