### ISSUE TITLE
Question how do i tell??

### ISSUE THREAD

**Issue by aday12345** [VahidN/EFSecondLevelCache.Core#34]
how do i tell of the objects i queried came from the cache or the database

**Comment by VahidN** [comment]
- You can use [EFCacheDebugInfo and its IsCacheHit](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.AspNetCoreSample/Controllers/HomeController.cs#L29) property.
- Or [log the generated SQL's by EF Core](http://thedatafarm.com/data-access/logging-in-ef-core-2-2-has-a-simpler-syntax-more-like-asp-net-core/).

**Comment by aday12345** [comment]
thanks
