### ISSUE TITLE
Variable item expiration

### ISSUE THREAD

**Issue by jasenf** [VahidN/EFSecondLevelCache.Core#37]
Hi again

What's the best way to implement specific cache expiration rules for a single query?  We have one query that needs to be refreshed much more frequently than the other 99% of queries.  It would be nice if there were a simple override to Cacheable() that just let us pass TotalSeconds to cache.

thanks!
jasen

**Comment by VahidN** [comment]
Added it via #https://github.com/VahidN/EFSecondLevelCache.Core/commit/97eb7dac2c05a5586b6c5ba669bd99d8589f0239
