### ISSUE TITLE
Invalid result from Cacheable when using FirstOrDefaultAsync

### ISSUE THREAD

**Issue by MoienTajik** [VahidN/EFSecondLevelCache.Core#38]
# Summary of the issue

When an argument passes to the `FirstOrDefaultAsync` method ( and this issue may exist for other methods like `ToListAsync`, `SingleAsync`, ... ), the `Cacheable` caches the results correctly, but when another argument with **different value** passes to it, it returns the **previous** results again.

Seems like the `Cacheable` method only differs and watch for different argument values just in the `Where` clause, not the `FirstOrDefaultAsync`, `SingleOrDefaultAsync` and other **EntityFramework.Core** methods, because different argument values work correctly by using `Where` method.

I know that the `Cacheable` is written on top of `IQueryable` and it caches the result based on the `Query`, but with that, we're unable to use the **Microsoft.EntityFramework.Core** [queryable extensions](https://github.com/aspnet/EntityFrameworkCore/blob/78476005b30ff201d4523d24da090ce6c84fb248/src/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.cs) anymore.

## Environment

```
The in-use version: 
EFSecondLevelCache.Core v1.8.1
CacheManager.Microsoft.Extensions.Caching.Memory v1.2.0
```

## Example code/Steps to reproduce:

```
// Cache userA correctly here
var userA = await context.Users
	.Cacheable()
	.FirstOrDefaultAsync(user => user.Username == "ABC", cancellationToken);
	
// In this query Cacheable returns previous result (userA) again, But the username is different now!
var userB = await context.Users
	.Cacheable()
	.FirstOrDefaultAsync(user => user.Username == "EFG", cancellationToken);


// By using Where clause, arguments cache properly.

// Returns UserA based on "ABC" username.
var userA = await context.Users
	.Where(user => user.Username == "ABC")
	.Cacheable()
	.FirstOrDefaultAsync(cancellationToken);

// Returns UserB based on "EFG" username.
var userB = await context.Users
	.Where(user => user.Username == "EFG")
	.Cacheable()
	.FirstOrDefaultAsync(cancellationToken);
```

**Comment by VahidN** [comment]
True. It doesn't see anything after the `Cacheable()` method. For these cases, add a `Where()` method before the `.Cacheable()` method for `FirstOrDefaultAsync`/ SingleOrDefaultAsync() cases:
```csharp
var ad = context.Analytics.FirstOrDefault(x => x.ID == a.ID);
// change it to
var ac = context.Analytics.Where(x => x.ID == a.ID).Cacheable(debugger).FirstOrDefault();
```

**Comment by MoienTajik** [comment]
This could be better at least by writing a Roslyn Analyzer for queries which are using `Cacheable` to get a warning/error at compile time. I can write that and open a pull request if you're ok with it.

**Comment by VahidN** [comment]
Fixed it via #https://github.com/VahidN/EFSecondLevelCache.Core/commit/17a44e4da90fed372cfd12e7d797683793120d8a. Now it sees the whole expression tree.
