### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by jasenf** [VahidN/EFSecondLevelCache.Core#45]
Not quite sure why this conversation was locked but its particularly important.

Essentially this lib doesn't work on multiple instances of the same app with a shared Redis cache.  Not really sure I see the purpose of Redis is that's that case.  This is a huge huge issue IMO and one we should discuss.

_Originally posted by @VahidN in https://github.com/VahidN/EFSecondLevelCache.Core/issues/44

**Comment by VahidN** [comment]
I have no plan about. Doesn't work for you, Don't use it
