### ISSUE TITLE
FileNotFound

### ISSUE THREAD

**Issue by kooshanabedian** [VahidN/EFSecondLevelCache.Core#51]
# Summary of the issue

FileNotFoundException: Could not load file or assembly 'EFSecondLevelCache.Core, Version=2.6.3.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified

## Environment

```
.NET Core SDK version: 3.0.100-preview9-014004 
Microsoft.EntityFrameworkCore version: 3.0.0-preview9.19423.6
EFSecondLevelCache.Core version: 2.6.3
```

## Output:

```
Exception message:
FileNotFoundException: Could not load file or assembly 'EFSecondLevelCache.Core, Version=2.6.3.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified
```

**Comment by VahidN** [comment]
Run these commands in the main folder of your app to update your entire solution consistently:
```
dotnet tool install -g dotnet-outdated
dotnet outdated -u
dotnet restore
```
