### ISSUE TITLE
Always returns first cached instance

### ISSUE THREAD

**Issue by kooshanabedian** [VahidN/EFSecondLevelCache.Core#53]
# Summary of the issue
It seems that always the first cached result is returned.

## Environment

```
.NET Core SDK version: 3.0.100-rc1-014190
Microsoft.EntityFrameworkCore version: 3.0.0-rc1.19456.14
EFSecondLevelCache.Core version: 2.6.4, [ 2.6.3 ]
```

## Example code/Steps to reproduce:

pretty basic setup indeed, with redis cache.
```
await dbContext.Brokers_Requests
                .Where(o =>  o.Id == request.Id)
                .Cacheable()
                .FirstOrDefaultAsync();
```

**Comment by kooshanabedian** [comment]
Note that the Id property is located on an aggregate base class and inherited by other classes, if it matters in any way.

**Comment by VahidN** [comment]
I can't reproduce it. [Try this sample](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.AspNetCoreSample/Controllers/HomeController.cs#L284).
Using 2 different parameters will create 2 different cache-keys with different results from the cache:
![issue53](https://user-images.githubusercontent.com/766010/65440795-257c1580-de36-11e9-821a-5a975848f051.png)

**Comment by kooshanabedian** [comment]
Indeed. Here is my sample for three different values for Id parameter. It generates three different records in Redis but all of them referencing the same hash.

Records:

![1](https://user-images.githubusercontent.com/24536134/65441746-cfa86d00-de37-11e9-8d3f-c6a9b56a812d.PNG)

1)
![2](https://user-images.githubusercontent.com/24536134/65441765-d3d48a80-de37-11e9-9a5b-a82c331d8d39.PNG)

2)
![3](https://user-images.githubusercontent.com/24536134/65441774-d9ca6b80-de37-11e9-96a1-0cbc73ad9901.PNG)

3)
![4](https://user-images.githubusercontent.com/24536134/65441796-e222a680-de37-11e9-9896-19f647346dd0.PNG)

Data:
![5](https://user-images.githubusercontent.com/24536134/65441800-e4850080-de37-11e9-8fae-075112d902bc.PNG)

**Comment by VahidN** [comment]
You are using V2.6.3. Please update it to 2.6.4, because it considers `ConstantExpression` value's in final hash. In this case you won't see the same cache-keys.

**Comment by kooshanabedian** [comment]
You are right. my bad. updating to 2.64. fixes the issue for cases where I directly use DbContext.
If I use some extension methods on DbContext to get some form of a repository pattern,
I'm stuck again. But I guess that's some misuse on my part.

```
public static async Task<TEntity> GetFirstOrDefaultAsync<TEntity,TDbContext>(this TDbContext dbContext, Expression<Func<TEntity, bool>>? predicate = null,
                                                Func<IQueryable<TEntity>, IOrderedQueryable<TEntity>>? orderBy = null,
                                                Func<IQueryable<TEntity>, IIncludableQueryable<TEntity, object>>? include = null,
                                                bool disableTracking = true,
                                                CancellationToken cancellationToken = default(CancellationToken))
            where TEntity : class
            where TDbContext : CacheawareDbContext
        {
            IQueryable<TEntity> query = dbContext.Set<TEntity>();
            if (disableTracking)
            {
                query = query.AsNoTracking();
            }

            if (include != null)
            {
                query = include(query);
            }

            if (predicate != null)
            {
                query = query.Where(predicate);
            }

            if (orderBy != null)
            {
                    return await orderBy(query)
                            .Cacheable(cacheExpirationMode,timeSpan.Value)
                            .FirstOrDefaultAsync(cancellationToken);
            }
            else
            {
                    return await query
                            .Cacheable(cacheExpirationMode,timeSpan.Value)
                            .FirstOrDefaultAsync(cancellationToken);
            }
        }
```

**Comment by VahidN** [comment]
[I tested your ext method](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.AspNetCoreSample/Controllers/HomeController.cs#L304) and it works fine (creates 2 different cache-keys for 2 different inputs):
![issue53_@](https://user-images.githubusercontent.com/766010/65445478-2cf3ec80-de3f-11e9-8b3a-72bc6b53f202.png)

**Comment by kooshanabedian** [comment]
Thank you for your help. I do very much appreciate it. I'm closing this now, since I couldn't track the core issue, which is obviously on my par.
