### ISSUE TITLE
Support order by?

### ISSUE THREAD

**Issue by johnkwaters** [VahidN/EFSecondLevelCache.Core#54]
I tried plugging in your cache, but I get this when i do an order by:

Unable to cast object of type 'EFSecondLevelCache.Core.EFCachedQueryable`1[MontagePortal.DTO.Base.CrmRefDTO]' to type 'System.Linq.IOrderedQueryable

**Comment by VahidN** [comment]
Yes, It does. [Follow these samples](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.AspNetCoreSample/Controllers/HomeController.cs#L32).

**Comment by johnkwaters** [comment]
So Cacheable has to come after OrderBy? In my case I don't want that. I want the client to be able to sort the cached results as they see fit.

**Comment by VahidN** [comment]
No. It's a LINQ to Entities cache only, not LINQ to Objects.
