### ISSUE TITLE
خطای AD0001

### ISSUE THREAD

**Issue by RezaAVS** [VahidN/EFSecondLevelCache.Core#57]
<div dir="rtl">
بعد از افزودن خط زیر خطای زیر مشاهده می شود

`            services.AddSingleton(typeof(ICacheManager<>), typeof(BaseCacheManager<>));
`

Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

**Comment by VahidN** [comment]
This issue is not related to this library. 
It has been reported here: https://github.com/dotnet/roslyn/issues/32287
And probably you should update your Visual Studio to fix it.
