### ISSUE TITLE
Just want to discuss improvement which i might be able to contribute

### ISSUE THREAD

**Issue by Rayvid** [VahidN/EFSecondLevelCache.Core#63]
# Summary of the issue
Thanks for a great library, I want to contribute to making it even greater.

I just want to make working with Microsoft.EntityFrameworkCore.Proxies more fluent. At the moment Cacheable appends AsNoTracking on originated query by default and to actually load inner properties when using Cacheable you need to do some magic as I did in a query I have provided as a sample

So the idea would be to add Include and ThenInclude extensions to EFCachedQueryable, what do you think?

And not sure if it's possible, to deproxy Entities automatically? Because if not you need to use `optionsBuilder.ConfigureWarnings(e => e.Ignore(CoreEventId.DetachedLazyLoadingWarning));` to it to work

## Environment

```
.NET Core SDK version: all
Microsoft.EntityFrameworkCore version: 3.1
EFSecondLevelCache.Core version: 2.9
```

## Example code/Steps to reproduce:
```
                    from rebate in _context.MMSRebates.Include(_ => _.FixedRebates).Include(_ => _.VariableRebates).Include(_ => _.IncentiveRebates)
                    from cust in _context.Customers.Where(_ => _.AcquirerId == acquirerID)
                        join hog in _context.MerchantGroupHOes on cust.Id equals hog.CustomerId
                        join merc in _context.Stores.Where(_ => _.IsActive) on hog.Id equals merc.MerchantGroupId
                    where merc.Id == rebate.EntityId || hog.Id == rebate.EntityId || cust.Id == rebate.EntityId
                    select new { Rebate = rebate, rebate.FixedRebates, rebate.VariableRebates, rebate.IncentiveRebates })
                        .Cacheable().ToList()
                        .Select(_ =>
                        {
                            var result = _.Rebate;
                            result.FixedRebates = _.FixedRebates;
                            result.VariableRebates = _.VariableRebates;
                            result.IncentiveRebates = _.IncentiveRebates;
                            return result;
                        });
```

**Comment by VahidN** [comment]
- You can use Include and ThenInclude (eager loading) by default and it's not necessary to do any changes about them. 
- Lazy loading of cached entities is meaningless. Because the second time that you are going to load them, it's not attached to any contexts. It seems there's a context in place, but it won't be used. At this time everything will be loaded from the cache and not from the database or its lazy loading proxies. So we don't need these proxies at all and that's why `AsNoTracking` method will be called on the original query to disable these proxies. We don't need them, because our cache containers only support eager loading of data.

**Comment by Rayvid** [comment]
Hi, well I'm in the situation getting hands-on on the project already using proxies and i managed to integrate your lib using that not very nice way I have illustrated with a code snippet. Don't you agree if to use Microsoft.EntityFrameworkCore.Proxies - you get detached proxies after Cacheable() call and need to use `optionsBuilder.ConfigureWarnings(e => e.Ignore(CoreEventId.DetachedLazyLoadingWarning));` and would be nice to have capability to "autodeproxy" those

**Comment by Rayvid** [comment]
Ok never mind, I found EFCore backlog where they plan to introduce conditional proxy creation prevention, I guess that will solve that kind of problems, no need to change this library to support proxies
