### ISSUE TITLE
Request support for Find / FindAsync

### ISSUE THREAD

**Issue by szavoda** [VahidN/EFSecondLevelCache.Core#8]
Request functionality to support Find / FindAsync calls.  When using a Generic Repository pattern, I use these functions to retrieve a record by Id where the Id is of type Object.

**Comment by VahidN** [comment]
Implemented via https://github.com/VahidN/EFSecondLevelCache.Core/commit/530ef43fa3f8dabbaf44829da6d9ac9f874fe0b2
```
PM> update-package
```
