### ISSUE TITLE
Caching entire tables

### ISSUE THREAD

**Issue by adamhathcock** [VahidN/EFSecondLevelCache.Core#9]
I'd like to do something like declare table `Address` be cached.

So the cache would aggressively cache the entire table and run queries like: `context.Buildings.Include(x => x.Address).ToListAsync()` and building data is gathered from the DB but the address include uses the cache data.

Does that make sense?  Does this currently work that?  Is it possible?

Thanks!

**Comment by VahidN** [comment]
This is a query caching library. The hash of each query will be computed plus other factors such as an optional user defined salt and then based on this hash, the related data will be retrieved form the cache. So each query will have a different hash and their data won't be shared.
